### ISSUE TITLE
Absolute #412

### ISSUE THREAD

**Issue by succmydecc** [Brittank88/Brittank88.github.io#3]
@Brittank88 since i cant talk in absolute github. i will here. https://github.com/absoIute/Mega-Hack-Pro-Future/issues/412, the extensions folder will be changed to geode. A mod loading system that HJFod and a few others are working on, absolute still is unsure but most likely he will ditch extensions for geode.

**Comment by absoIute** [comment]
it's not released yet so still a relevant issue, I am going to move to Geode though

**Comment by Brittank88** [comment]
Don't you dare start bloating my own **completely unrelated** repositories now @succmydecc. You were banned for being disruptive, take the hint.
